### ISSUE TITLE
Create Servers/Channels Done

### ISSUE THREAD

**Issue by patrickw098** [patrickw098/Tritone#4]
- [x]  Users can create servers
- [x]  Users can search for and join servers they are not members of using fuzzy search
- [x]  Users can click on servers to see the sub-channels of the server
- [x]  Users can create sub-channels within these servers
- [x]  Everything updates after an action

**Comment by s-pangburn** [comment]
- [x] I need to be able to edit and delete servers as well.
- [x] This also goes for channels!!
- [x] When switch the modal to Join Server, it doesn't seem to search for anything?
- [x] Any time I create a channel, it only gets added to High Five, no matter what server I'm in.
- [x] The Create New Channel input should have just a liiiittle margin on top to space it out.

**Comment by patrickw098** [comment]
- [x] Users can edit server names
- [x] Users can leave their servers
- [x] Admins (server creators) can delete channels within their servers
- [x] Admins (server creators) can edit channel names.

**Comment by s-pangburn** [comment]
- [x] Deleting channels doesn't seem to work for me, even for servers I create. I click the icon and the screen flickers, but nothing happens? 🤔 
- [ ] Also you should just make a server called "The quick brown fox jumps over the lazy dog" or something so that people find a match easier, haha. Or add more seeds! (This will be more important later, probably)

**Comment by s-pangburn** [comment]
:+1:
